language: objective-c
 
xcode_project: iTravelHel/iTravelHel.xcodeproj
xcode_scheme: iTravelHel/iTravelHelTests
xcode_sdk: iphonesimulator9.2
 
script:
- xcodebuild clean build test -project iTravelHel/iTravelHel.xcodeproj -scheme iTravelHel/iTravelHelTests
